### ISSUE TITLE
Make estimagic work with pandas 1.0

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#143]
### Current situation

Estimagic is only tested for pandas <= 0.25

### Desired Situation

Estimagic works for pandas 1.0 and older versions. 

### To-Do

I'm not sure which steps are necessary, but at least we need the following:

- [ ] Some pickled DataFrames cannot be loaded with the new pandas. We have to load them with an older pandas and save as something that is not .pickle. Then load it with the new pandas and pickle them. 
- [ ] Upgrade the test environments in tox.ini to use pandas 1.0 on all operating systems
- [ ] Add a new environment that uses an older pandas version. I think it's enough to do this only on linux, where tests much quicker than on the other systems. 

@tobiasraabe, @roecla @mo2561057 @amageh @ChristianZimpelmann Please add to-dos if you run into problems when upgrading pandas in your projects and think we have to do something in estimagic.
