### ISSUE TITLE
Improve estimation table and its documentation

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#270]
### Issues with current version estimation table

- The argument `sig_digits` does not actually implement a rounding to significant digits, but a simple rounding to a fixed number of decimal points. No other kind of rounding is implemented.
- The argument `left_decimals` is confusing and actually rather a hack to achieve padding that anything related to rounding.
- `sig_levels` is too abreviated
- The documentation is in matlab style, i.e. there are millions of examples for each argument instead of descriptions of arguments. There is also a rather long setup section before the first estimation table is shown. 

### To-Do Code

- [ ] rename `left_decimals` to padding and  incorporate the information that is currently only in the Notes into the description of that argument 
- [ ] rename `sig_levels` to `significance_levels`
- [ ] remove `sig_digits` argument
- Add a new argument called `rounding`. The following things would be valid for that argument:
    - An integer (which would specify the number of digits behind the decimal point)
    - A formatting string (see [here](https://mkaz.blog/code/python-string-format-cookbook/) for a few examples, [here](https://stackoverflow.com/questions/25780022/how-to-make-python-format-floats-with-certain-amount-of-significant-digits) for discussion of rounding to significant digits and [here](https://docs.python.org/3/library/string.html#format-specification-mini-language) for the full documentation of format strings (which is hard to read).
    - A function that takes a float and returns  string

### To-Do Documentation

The documentation should have the following sections:

1. A simple code example with associated output. All optional arguments should be left out but we should show how easy it is to combine statsmodels results with custom models. I would use the same example model as in the [ml tutorial](https://estimagic.readthedocs.io/en/stable/getting_started/first_likelihood_estimation_with_estimagic.html) and [msm tutorial](https://estimagic.readthedocs.io/en/stable/getting_started/first_msm_estimation_with_estimagic.html) so we can refer to the code there and load and show the result DataFrames which can then be compared to a OLS estimation using statsmodels. 
2. One example of an estimation table that uses multiple optional arguments at once and the associated output. In the end there should be a link to the API documentation that explains all optional arguments. Maybe this should use an example with more variables
3. One example that uses `return_type="python"`, does a modification to the DataFrame (e.g. drop a few rows and add a row called "controls" that has a checkmark in some columns and a cross in the others. 
4. A general description of the philosophy behind the estimation table that inspires to use it creatively
    - Why return type "python" can cover many usecases that are normally achieved with many arguments 
    - How outputs from any language can be brought into one of our "model" formats
    - ...

We should also link to that part of the documentation in all of our estimation examples. 

I also would replace all outputs by images of a latex table or an actual pdf instead of trying to render them in the notebook (it currently does not work). 

### Discussion

- Should we formally deprecate the old arguments or simply do the changes? I think we can simply do the changes. 
- What would be a good example for the more advanced sections? Should we stick to the example we are using currently in the estimation table documentation?

**Comment by hmgaudecker** [comment]
> here for discussion of rounding to significant digits

That link is not quite it, I think. Only looks after the decimal separator, right? 

One of my (and many others') pet peeves is that false sense of precision created by many tables. Like you see mean income of 38,234 Euros. Nobody cares about the 34 bit. People will start interpreting that (despite standard errors on the magnitude of hundreds), however, and miss the important bits.

Here is a function I have been using, probably got that from SO at some point, but cannot find the source.

```py
def nsf(num, n=3):
    """n-Significant Figures"""
    numstr = ("{0:.%ie}" % (n - 1)).format(num)
    return float(numstr)
```

**Comment by hmgaudecker** [comment]
It is `\sisetup{input-symbols=()}`, see here https://github.com/OpenSourceEconomics/estimagic/issues/253#issuecomment-974103608

**Comment by hmgaudecker** [comment]
Another trivial but useful return type would be `df`. Should probably be the default even. 

That is, return a dataframe with all the formatting of *** etc, which then takes advantage of the html rendering in a notebook. Currently, html looks ugly in notebooks.

**Comment by hmgaudecker** [comment]
Thinking of it, why think of it as two functions? 

1. Format results (i.e., return the python / modifiable stuff). Potentially have different options of returning strings only or numbers (already rounded)
2. Get the view in the output format you want

One may want to think of a short-hand again, but conceptually this might make sense?
