### ISSUE TITLE
Use modern pre-commit hooks and implement own

### ISSUE THREAD

**Issue by timmens** [OpenSourceEconomics/estimagic#413]
There are some interesting new pre-commit hooks that should be considered for the estimagic development, e.g. [refurbed](https://github.com/dosisod/refurb). Further, we should consider writing our own hook that checks that functions are called with keyword arguments and refactors them automatically. 

## Tasks

- [ ] Write a custom hook that checks the usage of args and kwargs in functions
- [ ] Delete hooks that we don't use
- [ ] Check if there are new hooks
