### ISSUE TITLE
Improve handling of notebooks in documentation

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/estimagic#422]
### What would you like to enhance and why? Is it related to an issue/problem?

We would like to execute most notebooks during each sphinx build, such that it becomes impossible to get outdated notebooks. Notebooks with very long runtime (e.g. [this](https://github.com/OpenSourceEconomics/estimagic/blob/main/docs/source/explanations/inference/bootstrap_montecarlo_comparison.ipynb)) or notebooks with optional dependencies need to be excluded.

See the discussion #420 for background.

### Tasks

- [ ] Extend the `rtd_environment.yml` file such that estimagic can actually run on readthedocs. Currently it does for example not contain numpy or scipy. 
- [ ] Add a pre-commit hook that deletes the output of all notebooks we want to execute during the sphinx build
- [ ] Set `nbsphinx_execute = "never"` to `nbsphinx_execute = "auto"` in `conf.py

### Potential alternatives

It is possible that this is still too demanding for readthedocs hardware. Last time we tried, we failed in the environment creation. In that case we could use a local pre-commit hook to run all notebooks that have changed.
